[package]
name = "crust_security"
version = "0.1.0"
edition = "2021"

[dependencies]
crust_core = { path = "../crust_core" }

[features]
byzantine = []
confidentiality = []
integrity = []
access_control = []
