apiVersion: v1
kind: ServiceAccount
metadata:
  name: crust-network-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crust-network-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crust-network-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: crust-network-account
    namespace: default
roleRef:
  kind: Role
  name: crust-network-role
  apiGroup: rbac.authorization.k8s.io
