apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crust
spec:
  selector:
    matchLabels:
      app: crust
  serviceName: crdt-service
  replicas: 3
  template:
    metadata:
      labels:
        app: crust
    spec:
      containers:
        - name: crust
          image: crust
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: crdt-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
