apiVersion: apps/v1
kind: Deployment
metadata:
  name: crust
spec:
  selector:
    matchLabels:
      app: crust
  template:
    metadata:
      labels:
        app: crust
    spec:
      containers:
        - name: crust
          image: crust
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
          ports:
            - containerPort: 3000
