FROM rust:1.83 as Builder
WORKDIR /usr/src/crust
COPY . .
RUN cargo build --release
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libssl-dev
COPY ../target/release/crust /usr/local/bin/crust
EXPOSE 5000
CMD [ "crust" ]