apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: crust-http
  delay:
    latency: "10ms"
    correlation: "100"
    jitter: "0ms"
